### PR TITLE
Only Block oAuthUser Registration and always allow SocialiteUser Registration.

### PR DESCRIPTION
**Pull request by yob-yob**
I had an issue where my Main User already exists in the database, so I need to link a socialite user to it, but then it doesn't allow me because the is-registration-enabled statement is blocking the part where it creates an oAuthUser and SocialiteUser...

it should only Block oAuthUser Registration and NOT SocialiteUser Registration.

### CODE REVIEW

**Comment by dododedodonl** [comment]
Thank you for the PR! Unfortunately, I am unable to accept the change as is, as it would change the current behaviour. I would accept the change if it were behind an extra config option that leaves current behaviour in place.

**Comment by yob-yob** [comment]
hmmm, I actually thought that this should be the main behaviour when I toggle `registration` in the config...

From what I understand, if `registration` is `false`... it should still allow me to use the `socialite-login` as long as I already have an account in the system with the same email address...

**Comment by dododedodonl** [comment]
I see the flow you describe being useful. Maybe the current naming is confusing, as `registration` also disables registering an existing user with a new socialite provider. The PR at this moment, changes the default behaviour. I am willing to merge a PR that adds another config value that enables the flow you describe (eg. `linking`) with defaults resulting in the behaviour as is.

**Comment by mrksdiehl** [comment]
I faced the same issue. Since -`>registration()` accepts a callback, I implemented a check on the user there and return `true` when the user exists.

```
->registration(function($user){
    /** @var User $user */
    if( $user && $user->hasAnyRole(Role::canAccessBackend()) ) {
        return true;
    }
    return false;
})
```

Not sure if this helps or if this is already outdated. Just wanted to share.

**Pull request closed without merging**
